name: Meson WebAssembly

on:
  push:
    branches: [ "myfreeer-patch-3" ]

env:
  wasmtime_version: v7.0.0
  wasmer_version: v3.1.1

jobs:
  build_wasi_sdk:
    strategy:
      matrix:
        C_FLAGS: ['', '-msimd128']
        wasi_sdk_version: [19, 20]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Downloading wasi-sdk
      run: |
        cd ${{github.workspace}}
        wget --no-verbose https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${{matrix.wasi_sdk_version}}/wasi-sdk-${{matrix.wasi_sdk_version}}.0-linux.tar.gz
        tar xf wasi-sdk-${{matrix.wasi_sdk_version}}.0-linux.tar.gz

    - name: Creating cross file
      run: |
        cat << EOF > ${{github.workspace}}/meson_cross_wasi.txt
        [host_machine] 
        system = 'wasi'
        cpu_family = 'wasm32'
        cpu = 'wasm32'
        endian = 'little'

        [binaries]
        c =  '${{github.workspace}}/wasi-sdk-${{matrix.wasi_sdk_version}}.0/bin/clang'
        ar = '${{github.workspace}}/wasi-sdk-${{matrix.wasi_sdk_version}}.0/bin/ar'
        ld = '${{github.workspace}}/wasi-sdk-${{matrix.wasi_sdk_version}}.0/bin/wasm-ld'
        strip = '${{github.workspace}}/wasi-sdk-${{matrix.wasi_sdk_version}}.0/bin/strip'

        [properties]
        c_args =      [ '-D_WASI_EMULATED_PROCESS_CLOCKS=1',  '-Wno-unused-parameter'] 
        c_link_args = [ '-lwasi-emulated-process-clocks']

        [cmake]

        CMAKE_FIND_ROOT_PATH_MODE_PROGRAM  = 'NEVER'
        CMAKE_FIND_ROOT_PATH_MODE_LIBRARY  = 'ONLY'
        CMAKE_FIND_ROOT_PATH_MODE_INCLUDE  = 'ONLY'
        CMAKE_FIND_ROOT_PATH_MODE_PACKAGE  = 'ONLY'
        EOF
        cat ${{github.workspace}}/meson_cross_wasi.txt


    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.3
      with:
        directory: build
        setup-options: --cross-file ${{github.workspace}}/meson_cross_wasi.txt --default_library=static -Dbuild_tests=true -Dc_args="${{matrix.C_FLAGS}}"
        action: test
