name: Meson WebAssembly

on:
  push:
    branches: [ "myfreeer-patch-3" ]

env:
  wasmtime_version: v7.0.0
  wasmer_version: v3.1.1

jobs:
  build_emsdk:
    strategy:
      matrix:
        C_FLAGS: ['', '-msse -msse2 -msse3 -msse4 -msimd128']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v13

    - name: Verify emsdk
      run: emcc -v

    - name: Creating cross file
      run: |
        cat << EOF > ${{github.workspace}}/meson_cross_emsdk.txt
        [binaries]
        c = '`which emcc`'
        cpp = '`which em++`'
        ar = '`which emar`'
        
        [properties]
        
        c_args = ['-D_WASI_EMULATED_PROCESS_CLOCKS=1']
        c_link_args = ['-s' 'STANDALONE_WASM', '-lwasi-emulated-process-clocks']
        cpp_args = ['-D_WASI_EMULATED_PROCESS_CLOCKS=1']
        cpp_link_args = ['-s' 'STANDALONE_WASM', '-lwasi-emulated-process-clocks']
        
        [host_machine]
        
        system = 'emscripten'
        cpu_family = 'wasm32'
        cpu = 'wasm32'
        endian = 'little'

        EOF
        cat ${{github.workspace}}/meson_cross_emsdk.txt

    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.3
      with:
        directory: build
        setup-options: --cross-file ${{github.workspace}}/meson_cross_emsdk.txt --default-library=static -Dbuild_tests=true
        action: test
